networks:
  eShop:
    driver: bridge

services:
  postgres:
    image: postgres
    ports:
      - "5434:5432"
    env_file:
      - ENVFiles/postgres.env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
        - eShop
 
  webapi:
    image: webapi
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
    env_file:
      - ENVFiles/WebAPI.env
    ports:
      - "5223:5223"
    networks:
      - eShop
  
    
#  client:
#    image: client
#    build:
#      context: ./client
#      dockerfile: Dockerfile
#    ports:
#      - "3000:3000"
#    depends_on:
#        - webapi
# 
volumes:
    postgres: